version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
        - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
        - 8081:8081
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: pass
    depends_on:
        - mongo

  jorgeliglabs.kata.dna.api:
    image: ${DOCKER_REGISTRY-}jorgeliglabskatadnaapi
    build:
      context: .
      dockerfile: JorgeligLabs.Kata.DNA.Api/Dockerfile
